# Generated by Django 2.2 on 2019-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=25)),
                ('label', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('main_image', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='board_of_members',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='board_of_members',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='board_of_members',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='board_of_members',
            name='id',
        ),
        migrations.AddField(
            model_name='board_of_members',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board_of_members',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board_of_members',
            name='member_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
