# Generated by Django 2.2 on 2019-12-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191208_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board_of_members',
            old_name='member_id',
            new_name='id',
        ),
    ]
