# Generated by Django 2.2 on 2019-12-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191210_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image4',
        ),
        migrations.AlterField(
            model_name='notisfication',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notisfication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
