# Generated by Django 2.2 on 2019-12-10 15:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191210_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
