# Generated by Django 2.2 on 2019-12-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191211_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board_of_members',
            options={'verbose_name_plural': 'Board Of Members'},
        ),
        migrations.AlterModelOptions(
            name='homeslideshow',
            options={'verbose_name_plural': 'Home Slideshow'},
        ),
        migrations.AlterModelOptions(
            name='randdslideshow',
            options={'verbose_name_plural': 'R&D Slideshow'},
        ),
        migrations.AlterModelOptions(
            name='team_members',
            options={'verbose_name_plural': 'Team Members'},
        ),
    ]
